name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Odpala się codziennie o północy
  workflow_dispatch:
  push:
    branches:
    - main
    - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: stvshy
          # Generujemy dwa osobne pliki: jeden dla jasnego motywu, drugi dla ciemnego
          outputs: |
            dist/github-snake-dark.svg?color_snake=#42b5fc&color_dots=#161b22,#4169E1,#6A5ACD,#8A2BE2,#9370DB
            dist/github-snake-light.svg?color_snake=#42b5fc&color_dots=#ebedf0,#4169E1,#6A5ACD,#8A2BE2,#9370DB

      - name: Push to repo
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output-snake # Tworzy osobną gałąź na węża
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
